<h1>Please fill the form and hit the button.</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('site/users', array('controller' => 'registration', 'action' => 'forgotten-password')));
$form->prepare();
?>
<div class="col-lg-8">
    <?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('email'));
            ?>
            <div class="col-lg-8">
                <?php   echo $this->formElement($form->get('email'));
                echo $this->formElementErrors($form->get('email'));?>
            </div>
        </div>

            <div class="form-group">
                <div class="col-lg-8 col-lg-offset-4">
                    <?php echo $this->formSubmit($form->get('submit'));?>
                </div>
            </div>
    </fieldset>
    <?php echo $this->form()->closeTag();?>

</div>