<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 31.03.2015
 * Time: 2:23
 */

?>
<table class="table" >
    <tr>
        <th>login</th>
        <th>email</th>
        <th>name</th>
        <th>last_name</th>
        <th>middle_name</th>
        <th>user_type</th>
        <th>birthday</th>
        <th>description</th>
        <th>institution</th>
        <th>sex</th>
        <th>phone</th>
    </tr>

    <?php foreach($data as $user) : ?>
    <tr>
        <td><?php echo $user->getLogin();?></td>
        <td><?php echo $user->getEmail();?></td>
        <td><?php echo $user->getName();?></td>
        <td><?php echo $user->getLastName();?></td>
        <td><?php echo $user->getMiddleName();?></td>
        <td><?php echo $user->getUserType()->getName()?></td>
        <td><?php echo $user->getBirthday()?></td>
        <td><?php echo $user->getDescription()?></td>
        <td><?php echo $user->getInstitution()->getName()?></td>
        <td><?php echo $user->getSex()->getType()?></td>
        <td><?php echo $user->getPhone()?></td>
    </tr>
<?php endforeach; ?>
</table>

