<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 31.03.2015
 * Time: 2:11
 */
$title = 'Add Institutions';
$this->headTitle($title);
//print $this->showMessages();
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('site/institutions', array('action' => 'add')));

$form->prepare();
?>
<div class="row">
<div class="col-lg-8">
    <?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <?php echo $this->formElement($form->get('id'));
        echo $this->formElementErrors($form->get('id'));?>
        <br>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('name'));
          ?>
            <div class="col-lg-8">
                <?php   echo $this->formElement($form->get('name'));
                echo $this->formElementErrors($form->get('name'));?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('institution_type_id'));
?>
            <div class="col-lg-8">
                <?php echo $this->formElement($form->get('institution_type_id'));
                echo $this->formElementErrors($form->get('institution_type_id'));?>
            </div>
        </div>

        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('address'));?>
            <div class="col-lg-8">
                <?php  echo $this->formElement($form->get('address'));
                echo $this->formElementErrors($form->get('address')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('subdomain'));
            ?>
            <div class="col-lg-8">
                <?php echo $this->formElement($form->get('subdomain'));
                echo $this->formElementErrors($form->get('subdomain')); ?>
            </div>
        </div>  <div class="form-group">
            <?php echo $this->formLabel($form->get('phone'));
            ?>
            <div class="col-lg-8">
                <?php echo $this->formElement($form->get('phone'));
                echo $this->formElementErrors($form->get('phone')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('description'));?>
            <div class="col-lg-8">
                <?php echo $this->formElement($form->get('description'));
                echo $this->formElementErrors($form->get('description'));?>
            </div>
        </div>



        <div class="form-group">
            <div class="col-lg-8 ">
                <?php echo $this->formSubmit($form->get('submit'));?>
            </div>
        </div>
    </fieldset>
    <?php echo $this->form()->closeTag();?>

</div>

