<?php
/**
 * Created by PhpStorm.
 * User: Vassya
 * Date: 31.03.2015
 * Time: 14:16
 */


?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('site/home') ?>">School</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url('site/home') ?>">Home</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Institution <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Schools</a></li>
                        <li><a href="#">Gardens</a></li>
                        <li><a href="#">University</a></li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url('site/institutions',array('action' => 'add')) ?>">Add</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign In <span class="caret"></span></a>
                    <ul class="dropdown-menu" style="background-color: #eee;">
                        <li >
                            <form method="post" action="<?php  echo $this->url('site/home',array('action' => 'login')) ?>" class="navbar-form navbar-right" role="search" style="margin-right: 1px;">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Login" >
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Password">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Sign In</button>
                                    <a href="#">Forgot password?</a>
                                </div>
                            </form>
                        </li>

                        <li class="divider"></li>

                        <li style="text-align: center;"><span style="color: #030303">Don't have an account?</span>
                            <div class="form-group">
                                <a href="<?php echo $this->url('site/users',array('action' => 'add')) ?>" class="btn btn-primary">Sign Up </a>
                            </div></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-right" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
            </form>
        </div><!--/.nav-collapse -->
    </div>
</nav>
