<?php
/**
 * Created by PhpStorm.
 * User: Vassya
 * Date: 31.03.2015
 * Time: 14:16
 */
?>
<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav nav-justified">
        <li><a href="#section1">Home</a></li>
        <li><a href="#section2">Profile</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#section3">Academic</a></li>
                <li><a href="#">Commercial</a></li>
                <li><a href="#">Financial</a></li>
                <li><a href="#">Interior Design</a></li>
                <li><a href="#">Medical</a></li>
                <li><a href="#">Religious</a></li>
            </ul>
        </li>
        <li><a href="#section4">Location</a></li>
        <li><a href="#section5">User</a></li>
        <li>
            <form class="form-inline">
                <div class="form-group">
                    <label class="sr-only">Search</label>
                    <input type="search" class="form-control" id="exampleInputEmail3" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
        </li>
    </ul>
</div>