<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 31.03.2015
 * Time: 2:11
*/
$title = 'Add Institution Type';
$this->headTitle($title);
//print $this->showMessages();
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('site/institution-type', array('action' => 'add')));

$form->prepare();
?>
<div class="col-lg-8">
    <?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <?php echo $this->formElement($form->get('id'));
        echo $this->formElementErrors($form->get('id'));?>
        <br>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('name'));
            ?>
            <div class="col-lg-8">
                <?php   echo $this->formElement($form->get('name'));
                echo $this->formElementErrors($form->get('name'));?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-8 ">
                <?php echo $this->formSubmit($form->get('submit'));?>
            </div>
        </div>
    </fieldset>
    <?php echo $this->form()->closeTag();?>

</div>

