<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 02.04.2015
 * Time: 11:35
 */ ?>



<table class="table" >
    <tr>
        <th>Name</th>
        <th>address</th>
        <th>subdomain</th>
        <th>phone</th>
        <th>description</th>
        <th>institution_type</th>
    </tr>

    <?php foreach($data as $institution) : ?>
        <tr>
            <td><?php echo $institution->getName();?></td>
            <td><?php echo $institution->getAddress();?></td>
            <td><?php echo $institution->getSubdomain();?></td>
            <td><?php echo $institution->getPhone();?></td>
            <td><?php echo $institution->getDescription();?></td>
            <td><?php echo $institution->getInstitutionType()->getName();?></td>
        </tr>
    <?php endforeach; ?>
</table>