<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/default/bootstrap.min.css')) ?>

    <?php echo $this->headScript()
       // ->prependFile($this->basePath('//html5shim.googlecode.com/svn/trunk/html5.js'))
        ->prependFile($this->basePath('//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js'))
        ->prependFile($this->basePath('js/the_firm/bootstrap.min.js'), 'text/javascript')
        ->prependFile($this->basePath('http://maps.googleapis.com/maps/api/js?sensor=false&extension=.js&output=embed'))
        ->prependFile($this->basePath('js/the_firm/scripts.js'),   'text/javascript' )
        ->prependFile($this->basePath('js/jquery.min.js'),   'text/javascript' )
        ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript' )
    ; ?>

</head>
<body onload="initialize()">

<?php echo $this->menuHelper() ?>

<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; <?php echo date('Y') ?> by Project 3 Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div> <!-- /container -->



</body>
</html>