<?php echo $this->messages; ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('site/home', array('action' => 'login')));
$form->prepare();
echo  $this->form()->openTag($form);
// echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('login'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('rememberme'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<?php // view helper

if ($user = $this->identity() ) {
    echo 'Logged in as ' . $this->escapeHtml($user->getLogin());
    ?>
    | <a href="<?php echo $this->url('site/home', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a>
<?php
} else {
    echo 'Not logged in';
}
?>
<p>
    <a href="<?php echo $this->url('site/users', array('controller' => 'users', 'action' => 'add'));?>"><?php echo $this->translate('Register'); ?></a> |
    <a href="<?php// echo $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>