<?php if ($user = $this->identity()): ?>
    <div class="form-group">
        <a href="<?php echo $this->url('site/home', array('controller' => 'index', 'action' => 'logout'));?>" class="btn btn-primary"><?php echo $this->translate('Sign Out'); ?></a>
    </div>
<?php else: ?>
    <?php echo $this->messages; ?>
    <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('site/home', array('action' => 'login')));
        //die($this->url('site/home', array('action' => 'login')));
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
    ?>

            <?php echo  $this->form()->openTag($form);?>
            <div class="form-group">
                <div class="col-lg-4">
                    <?php echo $this->formRow($form->get('login')) ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-4">
                    <?php echo $this->formRow($form->get('password')) ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-4">
                    <?php echo $this->formSubmit($form->get('submit')) ?>
                    <span><?php echo $this->formRow($form->get('rememberme')) ?></span>
                </div>
            </div>


            <div class="form-group">
                <div class="col-lg-4">
                    <span>Don't have an account?</span>
                    <a href="<?php echo $this->url('site/users',array('action' => 'add')) ?>" class="btn btn-primary">Sign Up </a>
                    <br>
                    <a href="<?php echo $this->url('site/users',array('action' => 'forgotten-password')) ?>" >Forgotten Password </a>
                </div>
            </div>
            <?php echo $this->form()->closeTag() ?>
<?php endif ?>